### ISSUE TITLE
Add support for rails migrations

### ISSUE THREAD

**Issue by andrew-newell** [IlluminusLimited/pgdice#10]
When users need to add indexes to tables, the db barfs on the migration because the table is partitioned. It would be nice to capture that and apply that migration to all the expected tables, then continue on. 

Same with index removal I figure.

**Comment by scytherswings** [comment]
This would be a stretch goal, it seems like it would take some doing to get right.

**Comment by scytherswings** [comment]
In addition, I think this should be supported by Postgres 11. So those of us on RDS might end up getting that for free once Amazon releases support.

**Comment by scytherswings** [comment]
I think this isn't a feature worth implementing since it will be solved by Postgres 11.
