### ISSUE TITLE
Running rails generators causes invalid configuration error

### ISSUE THREAD

**Issue by andrew-newell** [IlluminusLimited/pgdice#15]
`rails g sidekiq:worker pgdice` caused this error to be thrown:
```
...gems/pgdice-0.2.1/lib/pgdice/configuration.rb:59:in `database_url': PgDice is not configured properly. database_url must be present! (PgDice::InvalidConfigurationError)
```

It looks like the root cause of this was that this environment variable wasn't set:
```
  config.database_url = ENV['PGDICE_DATABASE_URL']
```
Perhaps eager validation might not be a good thing?

**Comment by scytherswings** [comment]
This isn't a bug, this is a feature! (🤣 :trollface: )

Documentation has been updated to emphasize that yes, `database_url` is required and must be set to a usable value. If you don't want to do this then don't initialize PgDice.
