### ISSUE TITLE
PG::UnableToSend on broken network connections

### ISSUE THREAD

**Issue by andrew-newell** [IlluminusLimited/pgdice#19]
Not sure if this should be investigated or not, but closed connections cannot be reopened. Should this error be caught and cause a `PG::Connection.reset` or should this be left up to the user?

Technically the user can reset the connection using `PgDice.configuration.pg_connection.reset` but I'm not sure if that's a good experience or not.

**Comment by scytherswings** [comment]
I'm not entirely sure how this behavior should work. This needs to be used in production a bit more to know what the long term implications of this will be.

**Comment by andrew-newell** [comment]
This error is unrecoverable in a sidekiq scenario and needs to refresh the connection.
