### ISSUE TITLE
Allow users to specify timeout as argument 

### ISSUE THREAD

**Issue by andrew-newell** [IlluminusLimited/pgdice#20]
Some of the partitioning operations can take a while. It would be cool if you could pass in `timeout: 500` for how long that command should be allowed to take (database side).

**Comment by scytherswings** [comment]
This can likely be added pretty easily by using something like `SET statement_timeout to 600000;` on the database connection before executing the commands.

**Comment by andrew-newell** [comment]
This would not be possible without support in PgSlice, which isn't going to happen.
