### ISSUE TITLE
Sidekiq can't use symbols in arguments. PgDice uses symbols in arguments.

### ISSUE THREAD

**Issue by ghost** [IlluminusLimited/pgdice#29]
If you call PgDice through a Sidekiq worker, Sidekiq will JSONify the parameters to the worker. If you intend to pass those parameters to PgDice, they will not have any symbols in them at all. This causes a big issue if you want to be able to tweak PgDice behavior in async background jobs as you have to convert stringified hashes back to symbolized hashes which is dangerous and bad for performance.

PgDice needs to support hashes that only use JSON-safe types.

**Comment by scytherswings** [comment]
This, issue, while not ideal, isn't something I have the bandwidth to fix anytime soon. Contributions welcome, however!
