### ISSUE TITLE
Existing id_seq is reused from original table for newly partitioned tables

### ISSUE THREAD

**Issue by ghost** [IlluminusLimited/pgdice#9]
When an existing table is converted into a partitioned table, the id_seq associated with the id column should have its ownership changed to the new parent table. Currently the sequence is left being owned by the original table but this means you cannot safely drop the original partition.

**Comment by scytherswings** [comment]
Relates to #12

**Comment by scytherswings** [comment]
It might make sense to move this over only once the original table has been dropped.

**Comment by scytherswings** [comment]
This, issue, while not ideal, isn't something I have the bandwidth to fix anytime soon. Contributions welcome, however!
